[package]
name = "skia-safe"

description = "Safe Skia Bindings for Rust"
homepage = "https://github.com/rust-skia/rust-skia"
repository = "https://github.com/rust-skia/rust-skia"
readme = "README.md"
# 5 max
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf"]
# 6 max
categories = ["api-bindings", "graphics", "multimedia::images", "rendering::graphics-api", "visualization"] 
license = "MIT"

version = "0.14.4"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[features]
default = []
vulkan = ["skia-bindings/vulkan"]
svg = ["skia-bindings/svg"]
shaper = ["skia-bindings/shaper"]
paragraph = ["skia-bindings/paragraph", "shaper"]

[dependencies]
bitflags = "1.0.4"
skia-bindings = { version = "0.14.4", path = "../skia-bindings" }
# TODO: 1.3 breaks offscreen_gl_context
lazy_static = "=1.2"

[dev-dependencies]
# for skia-org
offscreen_gl_context = "0.23.0"
gleam = "0.6.16"
clap = "2.33.0"
ash = "0.29"
