[package]
name = "skia-safe"
version = "0.3.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[features]
default = []
vulkan = ["skia-bindings/vulkan"]

[dependencies]
bitflags = "1.0"
skia-bindings = { path = "../skia-bindings" }
lazy_static = "1.2"

[dev-dependencies]
glutin = "0.20"
clap = "2.32"