[package]
name = "skia-safe"

description = "Safe Skia Bindings for Rust"
homepage = "https://github.com/rust-skia/rust-skia"
repository = "https://github.com/rust-skia/rust-skia"
readme = "README.md"
# 5 max
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf"]
# 6 max
categories = ["api-bindings", "graphics", "multimedia::images", "rendering::graphics-api", "visualization"] 
license = "MIT"

version = "0.23.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[lib]
doctest = false

[features]
default = []
vulkan = ["skia-bindings/vulkan"]
svg = ["skia-bindings/svg"]
shaper = ["skia-bindings/shaper"]
textlayout = ["skia-bindings/textlayout", "shaper"]

[dependencies]
bitflags = "1.0.4"
skia-bindings = { version = "=0.23.0", path = "../skia-bindings" }
lazy_static = "1.4"

[dev-dependencies]
# for skia-org
# 0.25.1 fails to build on iOS targets on macOS: https://github.com/servo/rust-offscreen-rendering-context/pull/150 
offscreen_gl_context = { git = "https://github.com/servo/rust-offscreen-rendering-context", rev = "1b9c74737635add2b9076e12df129cc3326c1287" }
# offscreen_gl_context = "0.25.1"
# for offscreen_gl_context 0.25
# sparkle 0.1.9 fails to compile on macOS targeting aarch64-linux-android
sparkle = "0.1.10"
clap = "2.33.0"
ash = "0.29"
serial_test = "0.3"
serial_test_derive = "0.3"
