jobs:
- job: "${{ parameters.name }}"
  strategy:
    matrix:
      stable:
        toolchain: stable
        features: ''
        exampleArgs: '--driver cpu --driver pdf'
      beta:
        toolchain: beta
        features: ''
      stable-vulkan:
        toolchain: stable
        features: 'vulkan'
      stable-svg:
        toolchain: stable
        features: 'svg'
        exampleArgs: '--driver svg'
  variables:
    platform: ${{ parameters.platform }}
    image: ${{ parameters.image }}
    target: ${{ parameters.target }}
    runBinaries: ${{ parameters.runBinaries }}
    rust_backtrace: 1
    release_branch: 'release'
  pool:
    vmImage: $(image)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.x'
      addToPath: true
      architecture: 'x64'

  - ${{ if eq(parameters.platform, 'macOS') }}:
    # macOS
    - script: |
        sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
      displayName: Install SDK Headers

  - ${{ if ne(parameters.platform, 'Windows') }}:
    # Linux and macOS.
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TOOLCHAIN
        $HOME/.cargo/bin/rustup component add rustfmt --toolchain $TOOLCHAIN
        $HOME/.cargo/bin/rustup component add clippy --toolchain $TOOLCHAIN
        $HOME/.cargo/bin/rustup target add $TARGET
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install Rust, Rustfmt, and Clippy

  - ${{ if eq(parameters.platform, 'Windows') }}:
    # Windows.
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --default-toolchain %TOOLCHAIN%
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        choco install llvm --version 8.0.0
      displayName: Install Rust and LLVM on Windows

  # All platforms.
  - script: |
        rustc -Vv
        cargo -V
    displayName: Rust & Cargo Versions

  - ${{ if ne(parameters.platform, 'Windows') }}:
    # Linux and macOS.
    - script: |
        clang --version
      displayName: LLVM/Clang Version

  - ${{ if eq(parameters.platform, 'Windows') }}:
    # Windows.
    - script: |
        "C:/Program Files/LLVM/bin/clang.exe" --version
      displayName: LLVM/Clang Version

  - ${{ if eq(parameters.target, 'aarch64-linux-android') }}:
    # Android NDK (macOS only for now)
    - bash: |
        set -e
        (cd /tmp && curl -sSf -o android-ndk.zip https://dl.google.com/android/repository/android-ndk-r18b-darwin-x86_64.zip)
        (cd /tmp && unzip android-ndk.zip)
        (cd /tmp/android-ndk-r18b && build/tools/make_standalone_toolchain.py --arch arm64 --install-dir /tmp/ndk)
        echo "##vso[task.setvariable variable=PATH;]${PATH}:/tmp/ndk/bin"
        echo "##vso[task.setvariable variable=ANDROID_NDK;]/tmp/android-ndk-r18b"
      displayName: 'Install Android NDK'

  # Note: support to ignore specific rust files and directories is unstable yet: https://github.com/rust-lang/rustfmt/pull/2522
  - bash: |
      set -e
      echo "// WAITING FOR RUSTFMT.TOML TO SUPPORT IGNORING FILES" >skia-bindings/src/bindings.rs
      cargo fmt -- --check
      rm skia-bindings/src/bindings.rs
    displayName: Check Rust formatting

  # Note: features are ignored when set in the workspace. This is a known bug in cargo (#5015), so cd into skia-safe instead.
  - bash: |
      set -e
      cd skia-safe && cargo build --release --features "$(features)" --all-targets --target $(target) -vv
      export SKIA_BINARIES_TAG=$(cat "$(Build.ArtifactStagingDirectory)/skia-binaries/tag.txt")
      export SKIA_BINARIES_KEY=$(cat "$(Build.ArtifactStagingDirectory)/skia-binaries/key.txt")
      echo "##vso[task.setvariable variable=SKIA_BINARIES_TAG;]${SKIA_BINARIES_TAG}"
      echo "##vso[task.setvariable variable=SKIA_BINARIES_KEY;]${SKIA_BINARIES_KEY}"
    displayName: Build all targets in skia-safe

  # Note: Clippy freshness check is independent from the freshness check of the build.
  # So we check the skia-bindings with the regular set of checks and skia-safe with warnings as errors after that.
  # Also: Windows is disabled for now, because the clippy freshness
  # check does seems to _always_ pick up skia-bindings when we want to check skia-safe with -D warnings.
  - ${{ if ne(parameters.platform, 'Windows') }}:
    - bash: |
        set -e
        (cd skia-bindings && cargo clippy --release --features "$(features)" --target $(target))
        (cd skia-safe && cargo clippy --release --features "$(features)" --all-targets --target $(target) -- -D warnings)
      displayName: Clippy skia-bindings and skia-safe

  - script: cd skia-safe && cargo test --release --features "$(features)" --target $(target) -vv
    displayName: Test skia-safe
    condition: and(succeeded(), eq(variables['runBinaries'], True))

  - script: cd skia-safe && cargo run --release --features "$(features)" --target $(target) --example skia-org "$(Build.ArtifactStagingDirectory)/skia-org" $(exampleArgs)
    displayName: Generate skia-org Example Images
    condition: and(succeeded(), ne(variables['exampleArgs'], ''), eq(variables['runBinaries'], True))

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/skia-org'
      artifactName: 'skia-org-examples-$(platform)-$(toolchain)'
    condition: and(succeeded(), ne(variables['exampleArgs'], ''), eq(variables['runBinaries'], True))

  - task: ArchiveFiles@2
    condition: and(succeeded(), eq(variables['toolchain'], 'stable'), eq(variables['Build.SourceBranchName'], variables['release_branch']))
    displayName: 'Archive binaries'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/skia-binaries'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/skia-binaries-$(SKIA_BINARIES_KEY).tar.gz'

  - task: GithubRelease@0
    condition: and(succeeded(), eq(variables['toolchain'], 'stable'), eq(variables['Build.SourceBranchName'], variables['release_branch']))
    displayName: 'Release to GitHub rust-skia/skia-binaries'
    inputs:
      action: 'edit'
      gitHubConnection: 'rust-skia-github-connection'
      repositoryName: 'rust-skia/skia-binaries'
      tagSource: 'manual'
      target: 'master'
      tag: '$(SKIA_BINARIES_TAG)'
      assets: '$(Build.ArtifactStagingDirectory)/skia-binaries-$(SKIA_BINARIES_KEY).tar.gz'
      assetUploadMode: 'replace'
      isPreRelease: true
      addChangeLog: false
