stages:

- stage: 'Build'
  jobs:
  - template: 'azure-pipelines-template.yml'
    parameters:
      platform: 'Linux'
      platformTarget: 'x86_64-unknown-linux-gnu'
      androidHost: 'linux-x86_64'
      androidNDK: 'r20'
      androidAPILevel: '26'
      androidBinExt: ''
      image: 'ubuntu-16.04'

  - template: 'azure-pipelines-template.yml'
    parameters:
      platform: 'macOS'
      platformTarget: 'x86_64-apple-darwin'
      androidHost: 'darwin-x86_64'
      androidNDK: 'r20'
      androidAPILevel: '26'
      androidBinExt: ''
      image: 'macOS-10.14'

  - template: 'azure-pipelines-template.yml'
    parameters:
      platform: 'Windows'
      platformTarget: 'x86_64-pc-windows-msvc'
      androidHost: 'windows-x86_64'
      androidNDK: 'r20'
      androidAPILevel: '26'
      androidBinExt: ''
      image: 'windows-2019'

- stage: 'Package'
  condition: and(succeeded(), eq(variables['build.SourceBranchName'], 'release'))
  jobs:
  - job:
    pool:
      vmImage: ubuntu-16.04
    variables:
      rust_backtrace: 1

    steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'

    - script: |
        rustc -Vv
        cargo -V
      displayName: 'Print versions'

    # skia-bindings gets packaged without verification, because the build process modifies the src directory.
    # TODO: reenable package verification as soon CLion and rust-analyzer supports !include macros.
    - bash: |
        set -e
        (cd skia-bindings && cargo package -vv --no-verify --target-dir /tmp/)
        mkdir -p "$(Build.ArtifactStagingDirectory)/package/"
        cp /tmp/package/skia-bindings-*.crate "$(Build.ArtifactStagingDirectory)/package/"
        # pseudo-verification:
        (cd /tmp/package && tar xzf skia-bindings-*.crate && rm skia-bindings-*.crate)
        (cd /tmp/package/skia-bindings-* && cargo build -vv --release)
      displayName: 'Package and Verify skia-bindings'

    # TODO: why does this fail with
    # error: 1 files in the working directory contain changes that were not yet committed into git:
    #   src/prelude.rs
    # to proceed despite this, pass the `--allow-dirty` flag
    # TODO: find a better way to extract the GITHUB_RELEASE_TAG
    - bash: |
        set -e
        cd skia-safe && cargo package -vv --no-verify --allow-dirty --target-dir "$(Build.ArtifactStagingDirectory)"
        export GITHUB_RELEASE_TAG=$(cd "$(Build.ArtifactStagingDirectory)/package" && find skia-safe-*.crate | cut -d'-' -f3 | cut -d'.' -f1-3)
        echo "##vso[task.setvariable variable=GITHUB_RELEASE_TAG;]${GITHUB_RELEASE_TAG}"
      displayName: 'Package skia-safe'

    - task: GithubRelease@0
      displayName: 'Release to GitHub rust-skia/rust-skia'
      inputs:
        action: 'edit'
        gitHubConnection: 'rust-skia-github-connection'
        repositoryName: 'rust-skia/rust-skia'
        tagSource: 'manual'
        target: 'release'
        tag: '$(GITHUB_RELEASE_TAG)'
        assets: '$(Build.ArtifactStagingDirectory)/package/*.crate'
        assetUploadMode: 'replace'
        isPreRelease: true
        addChangeLog: false
