[package]

name = "skia-bindings"

description = "Skia Bindings for Rust"
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf", "svg"]
homepage = "https://github.com/rust-skia/rust-skia"
repository = "https://github.com/rust-skia/rust-skia"
license = "MIT"

version = "0.14.0"
authors = ["LongYinan <lynweklm@gmail.com>", "Armin Sander <armin@replicator.org>"]
edition = "2018"
build = "build.rs"
links = "skia"
include = [ "Cargo.toml", "build.rs", "build_support.rs", "build_support/**/*.rs", "src/**/*.cpp", "src/lib.rs" ]

[features]
default = []
vulkan = []
svg = []

[dependencies]

[build-dependencies]
cc = "1.0.35"
# we'd like to reference specific bindgen versions here, because the generated
# bindings are platform dependent and critical to this project.
bindgen = "=0.51.0"

# for downloading and extracting prebuilt binaries:
curl = "0.4.22"
flate2 = "1.0.7"
tar = "0.4.24"

# for reading .cargo.vcs_info.json to get the repository sha1 in case we need the full build.
serde_json = "1.0.39"

# for finding python's executable and passing it to gn.
which = "2.0.1"
